### ISSUE TITLE
CT data

### ISSUE THREAD

**Issue by kennys-cs1105** [M3DV/pulmonary-tree-labeling#1]
Hello,  thank you for your contribution and your work looks great.
I would like to ask, the Google Drive you provided seems to only have mask files, how can I get the CT images.

**Comment by duducheng** [comment]
Hi @kennys-cs1105 ,

Thanks for your interest.

As we stated in the paper, this work is based on the shape, i.e., pulmonary tree mask. Due to privacy issue, we are not available to release the raw CT data. 

JC

**Comment by kennys-cs1105** [comment]
Ok, thanks anyway for your wonderful work.
